version: '2'
services:
  ubuntu-16-nginx-1.10.0-php-7.0-phpmyadmin-4.6:
    build: .
    image: ubuntu-16-nginx-1.10.0-php-7.0-phpmyadmin-4.6
    ports:
      - "8080:8080"
    user: "100000"
    environment:
      - "SUPERVISORD_LOGLEVEL=debug"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    hostname: mysql
    container_name: mysql
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: EnvVarHere
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: Password123!
